-- MySQL Script generated by MySQL Workbench
-- Wed Jun 16 16:35:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_108601505
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_108601505` ;

-- -----------------------------------------------------
-- Schema db_108601505
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_108601505` DEFAULT CHARACTER SET utf8 ;
USE `db_108601505` ;

-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_User` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `User_address` VARCHAR(45) NOT NULL,
  `User_phone_number` INT NOT NULL,
  `User_log_x` INT NOT NULL,
  `User_log_y` INT NOT NULL,
  `Ceate_datetime` DATETIME NOT NULL,
  `salt` CHAR(200) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `salt_UNIQUE` (`salt` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_User_credential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_User_credential` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_User_credential` (
  `User_credential_id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `hashpwd` VARCHAR(200) NOT NULL,
  `Create_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`User_credential_id`, `User_id`),
  UNIQUE INDEX `hashpwd_UNIQUE` (`hashpwd` ASC) VISIBLE,
  INDEX `Usercredential_id_User_id_fk_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `Usercredential_id_User_id_fk`
    FOREIGN KEY (`User_id`)
    REFERENCES `db_108601505`.`tbl_User` (`User_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_deliveryman`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_deliveryman` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_deliveryman` (
  `Delivery_man_id` INT NOT NULL,
  `Deliveryman_name` VARCHAR(100) NOT NULL,
  `Deliveryman_phone_number` INT NOT NULL,
  `Deliveryman_address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Delivery_man_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_coupon` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_coupon` (
  `Coupon_id` INT NOT NULL,
  `Oupon_name` VARCHAR(45) NOT NULL,
  `Promotion_code` VARCHAR(45) NOT NULL,
  `S_date` DATETIME NOT NULL,
  `D_date` DATETIME NOT NULL,
  PRIMARY KEY (`Coupon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_order` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_order` (
  `Order_id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Delivery_man_id` INT NOT NULL,
  `Coupon_id` INT NOT NULL,
  `Order_status` INT NOT NULL,
  `Restaurant_rating` INT NULL,
  `Delivery_rating` INT NULL,
  `Delivery_fee` INT NOT NULL,
  `Total_prize` INT NOT NULL,
  PRIMARY KEY (`Order_id`, `User_id`),
  INDEX `order_deliverymanid_deliveryman_id_idx` (`Delivery_man_id` ASC) VISIBLE,
  INDEX `order_couponid_coupon_id_idx` (`Coupon_id` ASC) VISIBLE,
  INDEX `order_userid_user_id_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `order_deliverymanid_deliveryman_id`
    FOREIGN KEY (`Delivery_man_id`)
    REFERENCES `db_108601505`.`tbl_deliveryman` (`Delivery_man_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_couponid_coupon_id`
    FOREIGN KEY (`Coupon_id`)
    REFERENCES `db_108601505`.`tbl_coupon` (`Coupon_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_userid_user_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `db_108601505`.`tbl_User` (`User_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_restaurant` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_restaurant` (
  `Restaurant_id` INT NOT NULL,
  `Restaurant_name` VARCHAR(45) NOT NULL,
  `Restaurant_phone_number` VARCHAR(45) NOT NULL,
  `Restaurant_address` VARCHAR(100) NOT NULL,
  `Restaurant_log_x` INT NOT NULL,
  `Restaurant_log_y` INT NOT NULL,
  `Business` INT NOT NULL,
  `Openningtime` TIME NOT NULL,
  `Closingtime` TIME NOT NULL,
  PRIMARY KEY (`Restaurant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_meals` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_meals` (
  `Meals_id` INT NOT NULL,
  `Restaurant_id` INT NOT NULL,
  `Meals_name` VARCHAR(45) NOT NULL,
  `Meals_price` INT NOT NULL,
  INDEX `meals_resraurant_id_restaurant_id_idx` (`Restaurant_id` ASC) VISIBLE,
  PRIMARY KEY (`Meals_id`),
  CONSTRAINT `meals_resraurant_id_restaurant_id`
    FOREIGN KEY (`Restaurant_id`)
    REFERENCES `db_108601505`.`tbl_restaurant` (`Restaurant_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_108601505`.`tbl_ordered_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_108601505`.`tbl_ordered_details` ;

CREATE TABLE IF NOT EXISTS `db_108601505`.`tbl_ordered_details` (
  `Order_id` INT NOT NULL,
  `Meals_id` INT NOT NULL,
  `Unit_price` INT NOT NULL,
  `Count` INT NOT NULL,
  INDEX `fk_tbl_ordered_details_tbl_order1_idx` (`Order_id` ASC) VISIBLE,
  INDEX `ordered_details_mealsid_meals_id_idx` (`Meals_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_ordered_details_tbl_order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `db_108601505`.`tbl_order` (`Order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ordered_details_mealsid_meals_id`
    FOREIGN KEY (`Meals_id`)
    REFERENCES `db_108601505`.`tbl_meals` (`Meals_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
